version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - wiremock
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cep_logs
    ports:
      - "5432:5432"
  wiremock:
    image: wiremock/wiremock
    ports:
      - "8081:8080"
    volumes:
      - ./wiremock:/home/wiremock